name: vnum
description: A library that enables value based enum behaviour using classes.
version: 1.2.6
homepage: https://github.com/AmirKamali/Flutter_Vnum

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  reflectable: ^3.0.5
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: any
  json_serializable: any
  test: ^1.20.1
  